defaults: &defaults
  working_directory: ~/api-docs
  docker:
    - image: circleci/ruby:2.4.1-node-browsers
version: 2
jobs:
  deploy:
    <<: *defaults
    steps:
      - run: ./deploy.sh

workflows:
  version: 2
  release:
    jobs:
      - deploy:
          filters:
            branches:
              only: ci