defaults: &defaults
  working_directory: ~/api-docs
  docker:
    - image: circleci/ruby:2.4.1-node-browsers
version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: bundle install
      - persist_to_workspace:
          root: .
          paths:
            - '*'
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/api-docs
      - run: bundle exec middleman build --clean
  build_and_deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/api-docs
      - run: ./deploy.sh

workflows:
  version: 2
  release:
    jobs:
      - install
      - build:
          requires:
            - install
          filters:
            branches:
              ignore: master
      - build_and_deploy:
          requires:
            - install
          filters:
            branches:
              only: master