defaults: &defaults
  working_directory: ~/api-docs
  docker:
    - image: circleci/ruby:2.4.1-node-browsers
version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - run: bundle install
  deploy:
    <<: *defaults
    steps:
      - run: ./deploy.sh

workflows:
  version: 2
  release:
    jobs:
      - install:
          filters:
            branches:
              only: ci
      - deploy:
          requires:
            - install
          filters:
            branches:
              only: ci